In [59]:
import pandas as pd

In [60]:
def import_dataset(file_path):
    try:
        dataset = pd.read_csv(file_path)
        print("Dataset imported successfully!")
        return dataset
    except Exception as e:
        print(f"An error occurred while importing the dataset: {e}")
        return None

In [61]:
condominios_fracoes = import_dataset('datasets/condominios_fracoes.csv')
condominios_fracoes = condominios_fracoes.map(lambda x: x.lower().strip() if isinstance(x, str) else x)
 
manutencoes_reparacoes = import_dataset('datasets/manutencoes_reparacoes.csv')
manutencoes_reparacoes = manutencoes_reparacoes.map(lambda x: x.lower().strip() if isinstance(x, str) else x)
 
ocorrencias_reclamacoes = import_dataset('datasets/ocorrencias_reclamacoes.csv')
ocorrencias_reclamacoes = ocorrencias_reclamacoes.map(lambda x: x.lower().strip() if isinstance(x, str) else x)

pagamentos_quotas = import_dataset('datasets/pagamentos_quotas.csv')
pagamentos_quotas = pagamentos_quotas.map(lambda x: x.lower().strip() if isinstance(x, str) else x)

Dataset imported successfully!
Dataset imported successfully!
Dataset imported successfully!
Dataset imported successfully!

In [62]:
condominios_fracoes.isnull().sum()

fração_id             0
condominio            0
bloco                 0
andar                 0
porta                 0
tipo_fracao           0
area_m2              42
quota_mensal          0
proprietario_nome     0
proprietario_nif      0
data_aquisicao       41
valor_aquisicao      57
situacao             61
dtype: int64

In [63]:
manutencoes_reparacoes.isnull().sum()

manutencao_id        0
condominio           0
tipo_intervencao     0
area_afetada         0
descricao           23
data_reportada       0
data_inicio          0
data_conclusao      45
fornecedor          13
custo_total         15
urgencia             0
estado               0
dtype: int64

In [64]:
ocorrencias_reclamacoes.isnull().sum()

ocorrencia_id          0
fração_origem          0
tipo                   0
descricao_completa    28
data_ocorrencia        0
gravidade              0
resolvido              0
acao_tomada           18
dtype: int64

In [65]:
pagamentos_quotas.isnull().sum()

pagamento_id           0
fração_id              0
mes_referencia         0
data_vencimento        0
data_pagamento       752
valor_quota            0
multa                640
estado                 0
metodo_pagamento    1324
dtype: int64

In [66]:
condominios_fracoes[condominios_fracoes.duplicated(subset=[ 'fração_id', 'condominio', 'bloco', 'andar', 'porta', 'tipo_fracao',
       'area_m2', 'quota_mensal', 'proprietario_nome', 'proprietario_nif',
       'data_aquisicao', 'valor_aquisicao', 'situacao'], keep = False)].sort_values('fração_id')

,fração_id,condominio,bloco,andar,porta,tipo_fracao,area_m2,quota_mensal,proprietario_nome,proprietario_nif,data_aquisicao,valor_aquisicao,situacao
480,fr0001,condomínio central,c,8,8f,t2,87.5,129.44,josé fonseca sousa,0,2022-08-22,122563.63,ocupada
2331,fr0001,condomínio central,c,8,8f,t2,87.5,129.44,josé fonseca sousa,0,2022-08-22,122563.63,ocupada
711,fr0002,residencial atlântico,a,7,7e,t1,56.1,58.59,joana pinto simões,139257710,2007-04-21,57330.55,ocupada
1547,fr0002,residencial atlântico,a,7,7e,t1,56.1,58.59,joana pinto simões,139257710,2007-04-21,57330.55,ocupada
1119,fr0004,jardins da cidade,norte,4,4c,t2,70.3,79.95,fernando simões sousa,137591513,2009-11-10,66850.48,arrendada
2435,fr0004,jardins da cidade,norte,4,4c,t2,70.3,79.95,fernando simões sousa,137591513,2009-11-10,66850.48,arrendada
7,fr0005,condomínio central,c,5,5d,t3,124.2,178.97,antónio ramos sousa,125914876,2012-06-29,154259.41,ocupada
2151,fr0005,condomínio central,c,5,5d,t3,124.2,178.97,antónio ramos sousa,125914876,2012-06-29,154259.41,ocupada
801,fr0007,residencial atlântico,c,0,0e,t2,86.7,102.49,manuel marques rodrigues,101405605,2013-11-05,98386.31,arrendada
1161,fr0007,residencial atlântico,c,0,0e,t2,86.7,102.49,manuel marques rodrigues,101405605,2013-11-05,98386.31,arrendada
1514,fr0008,condomínio central,a,4,4f,t3,121.1,187.83,ana mendes almeida,120976569,2017-09-14,171582.75,ocupada
1815,fr0008,condomínio central,a,4,4f,t3,121.1,187.83,ana mendes almeida,120976569,2017-09-14,171582.75,ocupada
450,fr0009,quinta das palmeiras,b,0,0c,t2,70.7,73.05,alexandra ribeiro pinto,115206384,2022-02-27,110322.08,vazia
2421,fr0009,quinta das palmeiras,b,0,0c,t2,70.7,73.05,alexandra ribeiro pinto,115206384,2022-02-27,110322.08,vazia
348,fr0010,torres do sol,torre 1,8,8a,t3,101.3,185.30,tiago cardoso matos,251358994,2021-02-12,168460.72,vazia
1218,fr0010,torres do sol,torre 1,8,8a,t3,101.3,185.30,tiago cardoso matos,251358994,2021-02-12,168460.72,vazia

In [68]:
manutencoes_reparacoes.duplicated().sum()

np.int64(18)

In [67]:
manutencoes_reparacoes[manutencoes_reparacoes.duplicated(subset=[ 'manutencao_id', 'condominio', 'tipo_intervencao', 'area_afetada','descricao', 'data_reportada', 'data_inicio', 'data_conclusao','fornecedor', 'custo_total', 'urgencia', 'estado'], keep = False)].sort_values('manutencao_id')

,manutencao_id,condominio,tipo_intervencao,area_afetada,descricao,data_reportada,data_inicio,data_conclusao,fornecedor,custo_total,urgencia,estado
30,mn00031,quinta das palmeiras,manutenção preventiva,elevador,necessária inspeção periódica obrigatória,2024-07-05,2024-07-05,2024-07-08,primeworks group,2431.71,crítica,concluído
800,mn00031,quinta das palmeiras,manutenção preventiva,elevador,necessária inspeção periódica obrigatória,2024-07-05,2024-07-05,2024-07-08,primeworks group,2431.71,crítica,concluído
119,mn00120,vila verde,inspeção,garagem,marcações no chão necessitam repintura,2025-04-10,2025-04-11,2025-04-12,ultrafix & filhos,3150.53,crítica,concluído
811,mn00120,vila verde,inspeção,garagem,marcações no chão necessitam repintura,2025-04-10,2025-04-11,2025-04-12,ultrafix & filhos,3150.53,crítica,concluído
157,mn00158,quinta das palmeiras,melhoria,piscina,vedação de segurança danificada,2024-06-15,2024-07-04,2024-07-14,proserviços group,564.26,baixa,concluído
814,mn00158,quinta das palmeiras,melhoria,piscina,vedação de segurança danificada,2024-06-15,2024-07-04,2024-07-14,proserviços group,564.26,baixa,concluído
193,mn00194,quinta das palmeiras,melhoria,elevador,botões do painel não respondem,2024-06-05,2024-06-06,2024-06-10,primeworks group,5895.70,crítica,concluído
818,mn00194,quinta das palmeiras,melhoria,elevador,botões do painel não respondem,2024-06-05,2024-06-06,2024-06-10,primeworks group,5895.70,crítica,concluído
809,mn00201,torres do sol,reparação urgente,garagem,sistema de ventilação com problemas,2023-10-02,2023-10-07,2023-10-14,globaltec group,1310.78,alta,concluído
200,mn00201,torres do sol,reparação urgente,garagem,sistema de ventilação com problemas,2023-10-02,2023-10-07,2023-10-14,globaltec group,1310.78,alta,concluído
810,mn00251,quinta das palmeiras,manutenção preventiva,elevador,porta não fecha corretamente,2024-07-21,2024-08-25,2024-09-21,ultrafix group,3309.25,baixa,concluído
250,mn00251,quinta das palmeiras,manutenção preventiva,elevador,porta não fecha corretamente,2024-07-21,2024-08-25,2024-09-21,ultrafix group,3309.25,baixa,concluído
357,mn00358,vila verde,reparação urgente,jardim,sistema de rega avariado,2024-12-15,2024-12-17,2024-12-19,globaltec unipessoal,1273.65,crítica,concluído
801,mn00358,vila verde,reparação urgente,jardim,sistema de rega avariado,2024-12-15,2024-12-17,2024-12-19,globaltec unipessoal,1273.65,crítica,concluído
816,mn00387,residencial atlântico,manutenção preventiva,jardim,iluminação exterior fundida,2023-09-30,2023-10-07,2023-10-16,smartrepair solutions,588.62,alta,concluído
386,mn00387,residencial atlântico,manutenção preventiva,jardim,iluminação exterior fundida,2023-09-30,2023-10-07,2023-10-16,smartrepair solutions,588.62,alta,concluído
802,mn00405,quinta das palmeiras,reparação urgente,elevador,necessária inspeção periódica obrigatória,2024-10-09,2024-10-12,2024-10-16,ultrafix & filhos,4074.40,alta,concluído
404,mn00405,quinta das palmeiras,reparação urgente,elevador,necessária inspeção periódica obrigatória,2024-10-09,2024-10-12,2024-10-16,ultrafix & filhos,4074.40,alta,concluído
804,mn00441,jardins da cidade,melhoria,jardim,pragas detetadas nas plantas,2024-05-14,2024-05-17,2024-05-23,tecnoreparações solutions,454.68,alta,concluído
440,mn00441,jardins da cidade,melhoria,jardim,pragas detetadas nas plantas,2024-05-14,2024-05-17,2024-05-23,tecnoreparações solutions,454.68,alta,concluído
815,mn00442,torres do sol,reparação urgente,elevador,botões do painel não respondem,2023-12-22,2023-12-24,2023-12-26,masterfix unipessoal,5012.99,crítica,concluído
441,mn00442,torres do sol,reparação urgente,elevador,botões do painel não respondem,2023-12-22,2023-12-24,2023-12-26,masterfix unipessoal,5012.99,crítica,concluído
803,mn00484,condomínio central,manutenção preventiva,fachada,fissuras visíveis na parede norte,2025-01-01,2025-01-11,2025-01-30,ultrafix & filhos,1050.46,média,concluído
483,mn00484,condomínio central,manutenção preventiva,fachada,fissuras visíveis na parede norte,2025-01-01,2025-01-11,2025-01-30,ultrafix & filhos,1050.46,média,concluído
813,mn00522,jardins da cidade,inspecção,elevador,botões do painel não respondem,2024-04-05,2024-05-06,2024-05-27,ultrafix & filhos,1103.62,baixa,concluído
521,mn00522,jardins da cidade,inspecção,elevador,botões do painel não respondem,2024-04-05,2024-05-06,2024-05-27,ultrafix & filhos,1103.62,baixa,concluído
819,mn00625,jardins da cidade,manutencao preventiva,elevador,ruído excessivo durante funcionamento,2023-10-21,2023-10-22,2023-10-24,proserviços group,3392.98,crítica,concluído
624,mn00625,jardins da cidade,manutencao preventiva,elevador,ruído excessivo durante funcionamento,2023-10-21,2023-10-22,2023-10-24,proserviços group,3392.98,crítica,concluído
638,mn00639,residencial atlântico,inspeção,telhado,telhas partidas necessitam substituição,30/03/2025,2025-04-25,2025-05-18,proserviços sa,8007740.00,baixa,concluído
817,mn00639,residencial atlântico,inspeção,telhado,telhas partidas necessitam substituição,30/03/2025,2025-04-25,2025-05-18,proserviços sa,8007740.00,baixa,concluído
806,mn00675,torres do sol,reparação urgente,garagem,marcações no chão necessitam repintura,2024-10-10,2024-10-15,2024-10-25,proserviços sa,946.44,alta,concluído
674,mn00675,torres do sol,reparação urgente,garagem,marcações no chão necessitam repintura,2024-10-10,2024-10-15,2024-10-25,proserviços sa,946.44,alta,concluído
807,mn00746,residencial atlântico,manutenção preventiva,elevador,botões do painel não respondem,2025-01-23,2025-02-19,2025-03-20,masterfix lda,2867.55,baixa,concluído
745,mn00746,residencial atlântico,manutenção preventiva,elevador,botões do painel não respondem,2025-01-23,2025-02-19,2025-03-20,masterfix lda,2867.55,baixa,concluído
808,mn00792,jardins da cidade,reparação urgente,fachada,pintura descascada em várias zonas,2025-02-10,2025-02-15,2025-02-23,masterfix lda,2954.52,alta,concluído
791,mn00792,jardins da cidade,reparação urgente,fachada,pintura descascada em várias zonas,2025-02-10,2025-02-15,2025-02-23,masterfix lda,2954.52,alta,concluído

In [69]:
ocorrencias_reclamacoes.duplicated().sum()

np.int64(26)

In [72]:
ocorrencias_reclamacoes[ocorrencias_reclamacoes.duplicated(subset=['ocorrencia_id', 'fração_origem', 'tipo', 'descricao_completa','data_ocorrencia', 'gravidade', 'resolvido', 'acao_tomada'], keep = False)].sort_values('ocorrencia_id')

,ocorrencia_id,fração_origem,tipo,descricao_completa,data_ocorrencia,gravidade,resolvido,acao_tomada
177,oc00178,fr2285,ruído,obras não autorizadas no apartamento 5e fora d...,2024-07-10 16:43,2,true,morador notificado por escrito. situação regul...
1226,oc00178,fr2285,ruído,obras não autorizadas no apartamento 5e fora d...,2024-07-10 16:43,2,true,morador notificado por escrito. situação regul...
193,oc00194,fr0203,limpeza,empresa de limpeza não aparece há duas semanas...,2025-07-15 16:43,3,1,situação regularizada. empresa de limpeza noti...
1220,oc00194,fr0203,limpeza,empresa de limpeza não aparece há duas semanas...,2025-07-15 16:43,3,1,situação regularizada. empresa de limpeza noti...
214,oc00215,fr2227,estacionamento,"carro abandonado na garagem há meses, ocupando...",2025-01-25 16:43,3,false,em análise pela administração
1222,oc00215,fr2227,estacionamento,"carro abandonado na garagem há meses, ocupando...",2025-01-25 16:43,3,false,em análise pela administração
251,oc00252,fr1717,ruído,barulho excessivo proveniente do apartamento 4...,2024-09-03 16:43,3,false,em análise pela administração
1211,oc00252,fr1717,ruído,barulho excessivo proveniente do apartamento 4...,2024-09-03 16:43,3,false,em análise pela administração
259,oc00260,fr1583,vandalismo,caixas de correio arrombadas durante a noite. ...,2024-03-31 16:43,3,false,a resolver
1200,oc00260,fr1583,vandalismo,caixas de correio arrombadas durante a noite. ...,2024-03-31 16:43,3,false,a resolver
283,oc00284,fr0833,segurança,pessoas estranhas a entrar no edifício e a per...,2024-10-31 16:43,2,true,problema corrigido. sistema reparado/substituí...
1215,oc00284,fr0833,segurança,pessoas estranhas a entrar no edifício e a per...,2024-10-31 16:43,2,true,problema corrigido. sistema reparado/substituí...
301,oc00302,fr1979,ruído,cão do apartamento 1a ladra constantemente dur...,2025-04-22 16:43,2,false,pendente
1209,oc00302,fr1979,ruído,cão do apartamento 1a ladra constantemente dur...,2025-04-22 16:43,2,false,pendente
304,oc00305,fr0681,vandalismo,grafittis na entrada do bloco sul. necessária ...,2025-02-15 16:43,4,false,em análise pela administração
1206,oc00305,fr0681,vandalismo,grafittis na entrada do bloco sul. necessária ...,2025-02-15 16:43,4,false,em análise pela administração
1229,oc00310,fr1022,ruído,obras não autorizadas no apartamento 4d fora d...,2025-04-29 16:43,3,true,morador notificado por escrito. situação regul...
309,oc00310,fr1022,ruído,obras não autorizadas no apartamento 4d fora d...,2025-04-29 16:43,3,true,morador notificado por escrito. situação regul...
1208,oc00325,fr0029,estacionamento,"carro abandonado na garagem há meses, ocupando...",2025-03-13 16:43,4,true,proprietário do veículo identificado e notific...
324,oc00325,fr0029,estacionamento,"carro abandonado na garagem há meses, ocupando...",2025-03-13 16:43,4,true,proprietário do veículo identificado e notific...
423,oc00424,fr2142,infiltração,mancha de humidade no teto da sala com gotejam...,2025-08-31 16:43,4,false,em análise pela administração
1213,oc00424,fr2142,infiltração,mancha de humidade no teto da sala com gotejam...,2025-08-31 16:43,4,false,em análise pela administração
442,oc00443,fr1942,vandalismo,caixas de correio arrombadas durante a noite. ...,2024-09-25 16:43,1,true,limpeza realizada. apresentada queixa na políc...
1214,oc00443,fr1942,vandalismo,caixas de correio arrombadas durante a noite. ...,2024-09-25 16:43,1,true,limpeza realizada. apresentada queixa na políc...
1207,oc00468,fr2101,ruído,obras não autorizadas no apartamento 5e fora d...,2025-08-05 16:43,4,false,em análise pela administração
467,oc00468,fr2101,ruído,obras não autorizadas no apartamento 5e fora d...,2025-08-05 16:43,4,false,em análise pela administração
1204,oc00501,fr2480,limpeza,empresa de limpeza não aparece há duas semanas...,2024/07/11 16:43:25,2,false,a resolver
500,oc00501,fr2480,limpeza,empresa de limpeza não aparece há duas semanas...,2024/07/11 16:43:25,2,false,a resolver
1225,oc00540,fr0273,ruido,cão do apartamento 1a ladra constantemente dur...,2025-01-08 16:43,2,true,morador notificado por escrito. situação regul...
539,oc00540,fr0273,ruido,cão do apartamento 1a ladra constantemente dur...,2025-01-08 16:43,2,true,morador notificado por escrito. situação regul...
588,oc00589,fr0071,ruído,barulho excessivo proveniente do apartamento 3...,2024-07-03 16:43,5,true,morador notificado por escrito. situação regul...
1201,oc00589,fr0071,ruído,barulho excessivo proveniente do apartamento 3...,2024-07-03 16:43,5,true,morador notificado por escrito. situação regul...
632,oc00633,fr0308,ruído,obras não autorizadas no apartamento 4d fora d...,2024-06-16 16:43,3,true,morador notificado por escrito. situação regul...
1221,oc00633,fr0308,ruído,obras não autorizadas no apartamento 4d fora d...,2024-06-16 16:43,3,true,morador notificado por escrito. situação regul...
709,oc00710,fr1696,limpeza,empresa de limpeza não aparece há duas semanas...,2024-05-28 16:43,2,false,a resolver
1227,oc00710,fr1696,limpeza,empresa de limpeza não aparece há duas semanas...,2024-05-28 16:43,2,false,a resolver
869,oc00870,fr0050,segurança,pessoas estranhas a entrar no edifício e a per...,2024-05-23 16:43,2,true,problema corrigido. sistema reparado/substituí...
1205,oc00870,fr0050,segurança,pessoas estranhas a entrar no edifício e a per...,2024-05-23 16:43,2,true,problema corrigido. sistema reparado/substituí...
1210,oc00877,fr1818,ruído,barulho excessivo proveniente do apartamento 3...,2024-12-03 16:43,4,true,morador notificado por escrito. situação regul...
876,oc00877,fr1818,ruído,barulho excessivo proveniente do apartamento 3...,2024-12-03 16:43,4,true,morador notificado por escrito. situação regul...
1212,oc00887,fr0006,estacionamento,veículo estacionado no meu lugar de garagem (l...,29/06/2024 16:43,4,false,pendente
886,oc00887,fr0006,estacionamento,veículo estacionado no meu lugar de garagem (l...,29/06/2024 16:43,4,false,pendente
1223,oc00892,fr1254,estacionamento,"carro abandonado na garagem há meses, ocupando...",2025-04-18 16:43,3,false,a resolver
891,oc00892,fr1254,estacionamento,"carro abandonado na garagem há meses, ocupando...",2025-04-18 16:43,3,false,a resolver
1217,oc00914,fr1838,limpeza,lixo acumulado no patamar do 1º andar há vário...,2025-06-03 16:43,3,false,a resolver
913,oc00914,fr1838,limpeza,lixo acumulado no patamar do 1º andar há vário...,2025-06-03 16:43,3,false,a resolver
1219,oc00915,fr0503,ruído,barulho excessivo proveniente do apartamento 2...,2024-12-17 16:43,3,true,morador notificado por escrito. situação regul...
914,oc00915,fr0503,ruído,barulho excessivo proveniente do apartamento 2...,2024-12-17 16:43,3,true,morador notificado por escrito. situação regul...
1017,oc01018,fr2280,infiltração,"infiltração na parede da casa de banho, provav...",2024/03/24 16:43:26,3,true,reparação efetuada. canalização substituída e ...
1216,oc01018,fr2280,infiltração,"infiltração na parede da casa de banho, provav...",2024/03/24 16:43:26,3,true,reparação efetuada. canalização substituída e ...
1202,oc01111,fr0089,ruído,cão do apartamento 4d ladra constantemente dur...,2024-09-17 16:43,4,true,morador notificado por escrito. situação regul...
1110,oc01111,fr0089,ruído,cão do apartamento 4d ladra constantemente dur...,2024-09-17 16:43,4,true,morador notificado por escrito. situação regul...

In [73]:
pagamentos_quotas.duplicated().sum()

np.int64(96)

In [75]:
pagamentos_quotas.columns

Index(['pagamento_id', 'fração_id', 'mes_referencia', 'data_vencimento',
       'data_pagamento', 'valor_quota', 'multa', 'estado', 'metodo_pagamento'],
      dtype='object')

In [76]:
pagamentos_quotas[pagamentos_quotas.duplicated(subset=['pagamento_id', 'fração_id', 'mes_referencia', 'data_vencimento','data_pagamento', 'valor_quota', 'multa', 'estado', 'metodo_pagamento'], keep = False)].sort_values('fração_id')

,pagamento_id,fração_id,mes_referencia,data_vencimento,data_pagamento,valor_quota,multa,estado,metodo_pagamento
60246,pg053265,fr0052,2025-01,2025-02-07,2025-03-05,42.13,0.73,em atraso,mb way
53264,pg053265,fr0052,2025-01,2025-02-07,2025-03-05,42.13,0.73,em atraso,mb way
60288,pg045280,fr0076,2024-06,2024-07-08,2024-07-03,146.29,0.00,pago,transf.
45279,pg045280,fr0076,2024-06,2024-07-08,2024-07-03,146.29,0.00,pago,transf.
652,pg000653,fr0080,2025-05,2025-06-07,2025-07-17,63.22,1.69,em atraso,transferência
...,...,...,...,...,...,...,...,...,...
60339,pg041057,fr2433,2024-05,2024-06-07,2024-06-29,106.3,1.56,em atraso,transferência
36457,pg036458,fr2443,2025-08,2025-09-07,2025-09-04,144.73,0.00,pago,mb way
60313,pg036458,fr2443,2025-08,2025-09-07,2025-09-04,144.73,0.00,pago,mb way
7299,pg007300,fr2445,2025-06,2025-07-08,2025-07-09,158.83,0.00,pago,transferência
60283,pg007300,fr2445,2025-06,2025-07-08,2025-07-09,158.83,0.00,pago,transferência